# Generated by Django 2.2.16 on 2022-06-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220615_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('custom_moderator', 'Право удалять и редактировать любые отзывы и комментарии'), ('custom_admin', 'Может создавать и удалять произведения, категории и жанры. Может назначать роли пользователям')]},
        ),
    ]
